name = "amirsubqi"
main = "index.js"
compatibility_date = "2024-09-23"

# --- PERBAIKAN: GUNAKAN FORMAT TABEL & EKSPLISIT BINDING ---
[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
VITE_SUPABASE_URL = "https://ekyggonipxdjbzgkmxwr.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVreWdnb25pcHhkamJ6Z2tteHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzOTExMjUsImV4cCI6MjA4ODk2NzEyNX0.gdt9tT_ndtfUF38IY3FbkMsca4hpP4x0yv5uh1Ud2HY"




[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "amirsubqi"